### ISSUE TITLE
Expose the api endpoint

### ISSUE THREAD

**Issue by Cryptogevity** [Nim-Video/cogvideox-2b-img2vid#1]
Hi, is there anyway to expose an API endpoint and let the input be something like a prompt and return a video?

**Comment by Ostaph14** [comment]
Yep, you could just use fastapi. Make an endpoint which runs the cli using the os module, then returns a base64 string of the video, which can be grabbed once the CLI is done running. Since running the CLI using OS module will block runtime execution of application should be a fairly straightforward process.

**Comment by Cryptogevity** [comment]
cool thanks, got it !
